### ISSUE TITLE
International support for at least 4 languages

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#1]
The platform has to support at least four languages 

- Romanian
- Ukrainian
- English
- Russian

**Comment by lzomedia** [comment]
take

**Comment by beniamin** [comment]
I will continue this issue

**Comment by beniamin** [comment]
Stiu ca uk este locale code-ul pt ucraineana, dar in dropdown mi se pare ca arata ciudat
<img width="359" alt="Screenshot 2022-02-27 at 02 19 13" src="https://user-images.githubusercontent.com/811812/155863712-9ec1e2ce-a34f-4061-91e1-a3e0b729be3d.png">

**Comment by gheorghelupu17** [comment]
eventual in dropdown pune UA
