### ISSUE TITLE
[FE] Change labels on buttons on Homepage

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#110]
Please change the button texts on the Homepage. If they are coming from the json files then please merge that issue so they can display propper messages. 

1. 
The first button should say: Solicită cazare 
The second button should say: Ofera cazare 

![image](https://user-images.githubusercontent.com/45068169/156619819-d816c069-5e93-4c16-880f-8d6acbbfd8d0.png)

2. 
The button on the left should say: Solicita cazare
The button on the right should say: Ofera cazare

![image](https://user-images.githubusercontent.com/45068169/156619703-289af333-daf0-45a4-8eb9-f845e30385fd.png)

**Comment by mihaibrehar** [comment]
Preiau eu.

**Comment by mihaibrehar** [comment]
Please send the UA and RU translations.
