### ISSUE TITLE
[FE] Change text on success page

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#111]
There is no email displayed in the contact form. Change body text to

Formularul tău a fost transmis. În cel mai scurt timp, vei fi contactat.
Găsești informații utile de urgență pe dopomoha.ro.

**Comment by mihaibrehar** [comment]
On which page exactly? Contact form looks fine to me.
Screenshot / URL please.

**Comment by overeha** [comment]
http://un-acoperis.heroesof.tech/ro/request-help-thanks

**Comment by overeha** [comment]
my mistake. it was the request help form
