### ISSUE TITLE
[Critical] Picture upload error in Add offer form 

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#113]
![image](https://user-images.githubusercontent.com/45068169/156621772-67fa86b6-ab94-492f-bc7c-a275eeb16e06.png)

**Comment by valentin1009** [comment]
Eu nu pot reproduce. S-a rezolvat intre timp?
![image](https://user-images.githubusercontent.com/11985027/156652832-12e03c83-191e-474c-a273-ca697d5658c5.png)
