### ISSUE TITLE
[Important] Cannot acces my profile from menu

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#116]
If I posted an offer and did not confirm my account by clicking the email link I cannot enter My Profile from the main menu. This behaviour is correct. 

I cannot test if I can access my profile because I cannot confirm my account. Let us make sure that the My profile tab works. 

![image](https://user-images.githubusercontent.com/45068169/156622937-be1de491-50be-4aad-802a-b34bf1b83374.png)

**Comment by mihaibrehar** [comment]
I can confirm the account (reset passwd form works) but the profile link does not work. I will try to fix this.
