### ISSUE TITLE
[Critical] Error when trying to View details about a request

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#120]
I cannot view a request in the admin dashboard. 

If i click on the Vezi detalii button i get the error below
![vezi detalii](https://user-images.githubusercontent.com/45068169/156625227-ee1f40b3-09ad-441c-8210-c1d7697dd689.png)

![image](https://user-images.githubusercontent.com/45068169/156625208-2a667e89-a150-43dc-9067-9fb0f6a57757.png)

**Comment by beniamin** [comment]
Pagina de view pentru un help request nu a fost "reconstruita". Avem vreun fel de mock-up?

**Comment by mihaibrehar** [comment]
Asta era functionala din cate stiu. Probabil s-a schimbat un camp in tabela ua_regions SAU inregistrarea respectiva nu are deloc valoare pt campul de county_id.

S-a ajuns intr-o situatie ciudata in care cred ca se face confuzie intre judetele RO si judetele UA.

**Comment by valentin1009** [comment]
Incearca sa acceseze county din HelpRequest, dar relatia acolo nu are cum sa mearga, ca nu exista foreign key. County id gasesc la nivel de user (createdBy). Corect?
