### ISSUE TITLE
[Critical] Allocate does not work

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#121]
When I click on Allocate nothing happens. 
Additional question: In the Request number field (the first one) do i have to write the request no like ”#67” or just ”67”?

![image](https://user-images.githubusercontent.com/45068169/156625425-fb1b50fb-d9e7-47c5-99e3-1871287943b5.png)

**Comment by gheorghelupu17** [comment]
closed by #107 , need to be retested

**Comment by gheorghelupu17** [comment]
@overeha  il redeschizi tu daca e cazul ?
