### ISSUE TITLE
Admin dashboard tweaks required

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#122]
Please make some small checks and changes on the dashboard

- Remove the Help for Health Administration label on the right. and add the DSU logo and the Code for Romania logo
- Check why the stats do not reflect real numbers 
- Some of the counters should be removed. Remove 
                        - ”Numar total beneficiari de consultanta strangere fonduri”, 
                        - ”Numar total beneficiari de informare si indrumare medicala” 
                        - ”Numar total beneficiari de alte servicii”
- Change ”Numar total beneficiari de cazare” to ”Numar total de persoane cazate”
- Add another counter with ”Numar total de gazde verificate”

![image](https://user-images.githubusercontent.com/45068169/156626288-e66b077f-9a7f-496e-b08d-7c726ee473b7.png)

**Comment by valentin1009** [comment]
Preiau eu
