### ISSUE TITLE
MISC FE issues

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#136]
- [x] change titles in meniu Solicită cazare, Oferă cazare 
- [x] check labels pe formulare ca jumate sunt engleza si jumate sunt romana
- [x] change Viena placeholder cu Radauti
- [x] adauga in lista de tipuri de cazari pe langa Garsoniera, Apartament, Casa, Hotel/Pensiune, Alte spatii
- [x] mailul de confirmare de cont pentru ofer cazare are random engleza in el de verificat
- [ ] Mesaj de la platforma Un Acoperis  - titlu unic la toate mailurile
- [x] hide Notificari din Admin Dashboard

**Comment by Cosmin-Parvulescu** [comment]
I'll take a look at this tomorrow
