### ISSUE TITLE
[Must Have] Other people do not display in admin

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#143]
If I receive a request for a person that has a kid, or an old person in care, as an admin I should be able to see this information in the dashboard displayed under Other People:  
In the admin dashboard in the dedicated section the information does not display anything currently

![image](https://user-images.githubusercontent.com/45068169/156693644-85755684-3b89-4e7f-aa19-27cccc1382f6.png)

**Comment by sherbastian** [comment]
on it
