### ISSUE TITLE
[Must Have] Number of guests is limited to 127 

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#144]
For some reason the number of guests in a Housing offer is limited to 127. The limit should be higher than 10.000 (we also need to think of places such as stadiums for example) 

![image](https://user-images.githubusercontent.com/45068169/156694356-fbd0a8df-0db1-4043-8a3d-7c148d90d29a.png)

**Comment by sherbastian** [comment]
on it

**Comment by sherbastian** [comment]
vad ca aceeasi limitare exista si pe campurile max_guests, available_rooms, available_beds, available_bathrooms. Daca ne gandim in terms of stadioane, am sa le scot si pe acelea.

**Comment by sherbastian** [comment]
noua limita e impusa de db la 32,767
