### ISSUE TITLE
[Nice To Have] Add transliteration for known languages in dropdown selector

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#145]
Currently in the language selector we have Russian and Ukrainian written in the specific alphabet. Please add the transliteration in parantheses next to it because sometimes the form will be filled by NGOs or Police officers who cannot make the difference betweek the two. 

It should display  
УКРАЇНСЬКИЙ (Ukrainian) -  for EN
УКРАЇНСЬКИЙ (ucraineană) - for RO

русский (Russian) - for EN
русский (Rusă) - for RO

![image](https://user-images.githubusercontent.com/45068169/156801881-102fde09-44c5-418e-8907-d2f72d458d3d.png)

**Comment by idormenco** [comment]
on it
