### ISSUE TITLE
[Nice To Have] Clean-up and organize form UI

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#146]
The form is a bit hectic in terms of spacing. 

Please make sure that the checkboxes of fields sit together with the necessary labels and help texts. 
For instance here the checkbox for "Am persoane in grija...." is further from the dedicated help text (Bifeaza casuta.....) than the help text is from the next field. 

There are several visual inconsistencies in this form, please try to clean it up and align it properly. 

![image](https://user-images.githubusercontent.com/45068169/156802657-df8f7f73-dcae-4f29-9d3a-8e84c7d040b8.png)

**Comment by idormenco** [comment]
on it
