### ISSUE TITLE
[Must Have] Add info in the Terms and conditions page in admin dashboard

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#148]
The text displayed in the first step of every form (the legal conditions to offer or request accommodation) need to also be displayed in the Admin dashboard so that when the user logs in has acces to the information provided here. The info should be available in all four languages. 

Here is the [info that needs to be copied
](http://un-acoperis.heroesof.tech/ro/request-help)
Here is where it has to be displayed
![image](https://user-images.githubusercontent.com/45068169/156806030-8e88fea0-116a-4d59-9c8d-a71019d8b040.png)

**Comment by danut3101** [comment]
I will take me
