### ISSUE TITLE
[Must Have] Replicate same behavior for both Request and Offer on signup

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#150]
Currently, 
- if I submit a request, as a user I receive an email holding a copy of my request. There is no link towards the platform and no request for me to confirm my account. 
- if i submit a housing offer I receive an email asking me to confirm my account and then I can see my properties in my account and also add more properties and manage mine. 

The Refugee ( the user that requests housing) should also be able to log in to his account, and right now he does not have any way to do so.

**Comment by valentin1009** [comment]
Refugiatii pot sa faca ceva in momentul de fata? Eu nu am vazut pagini/continut pentru ei. Altfel spus: ce vad ei dupa ce se logheaza?

**Comment by beniamin** [comment]
working on it

**Comment by beniamin** [comment]
<img width="610" alt="Screenshot 2022-03-04 at 23 20 33" src="https://user-images.githubusercontent.com/811812/156843188-45819c41-3ecc-4f1a-a957-57df0607f5b4.png">

Refugiatul va primi 2 mailuri, unul pentru confirmarea mailul si restarea parolei si un al2lea mail care contine informatii despre cererea de gazduire.
