### ISSUE TITLE
[Must Have] Implement allocation duration

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#152]
If I allocate a Refugee to a Host I want to be able to select for how many days the Refugee will be staying with that host. 
I want to also have a dedicated section in the Admin dashboard where I can see a table with all allocated Refugees who have 1 day left before they leave their accommodation so I can get in touch with them and see if they need further support with housing and get a review from them.

**Comment by x-dragos** [comment]
Hello,

My coleague Toma Iulian will handle this task (toma.iulian@beecoded.ro)
