### ISSUE TITLE
[Must Have] Add Gov logo on screens

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#159]
Please add the Gov logo in the partners' bar. the same way it is displayed here on this platform.  http://sprijin-de-urgenta.heroesof.tech.s3-website-eu-west-1.amazonaws.com/

The logo should be visible both in the admin dashboard and the public website

**Comment by danut3101** [comment]
I will take me

**Comment by overeha** [comment]
Add the gov logo in the admin dashboard as well not just on the front screen.
