### ISSUE TITLE
 Create footer

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#2]
The footer 
![Footer](https://user-images.githubusercontent.com/95479576/155834576-25fdabfa-1b2c-4194-95fd-667508645913.png)

Links:
"Despre proiect" leading to About page
"Dopomoha.ro" - leading to https://dopomoha.ro/
"Codul sursa" 

Logos needed:
Code4Ro - leading to https://code4.ro/ro
PNG
![Code4](https://user-images.githubusercontent.com/95479576/155834614-3df99e4c-34b1-4b5a-8115-d2dddd71dba4.png)
SVG
![Code4](https://user-images.githubusercontent.com/95479576/155834616-2b01c528-4e4c-46e9-be6b-f1cfb44d617f.svg)

Code4Ro TaskForce - leading to https://code4.ro/ro
PNG
![Code4TF](https://user-images.githubusercontent.com/95479576/155834626-9a38bb3f-6328-4e78-bd36-211f30332447.png)
SVG
![Code4TF](https://user-images.githubusercontent.com/95479576/155834748-13e55c40-2678-4d48-897b-5ddf5647b300.svg)

**Comment by radRares1** [comment]
Ma ocup eu.

**Comment by vilenbejenaru** [comment]
I will take it
