### ISSUE TITLE
[URGENT] Change label in Step two in Offer Housing form

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#203]
The title here is in english, I cannot change it from the Admin dashboard. It must be in Romanian and it should say "Ofera cazare
<img width="1481" alt="Screenshot 2022-03-09 at 22 45 26" src="https://user-images.githubusercontent.com/45068169/157532807-9f9c0a3a-3ae9-4b5c-9c1a-4dfc578028ed.png">
"

**Comment by beniamin** [comment]
ma ocup eu
