### ISSUE TITLE
[URGENT] Fix typos across the platform - see list in issue

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#204]
- In the housing options list, in Romanian replace Apartment with **Apartament**
<img width="266" alt="Screenshot 2022-03-09 at 22 48 11" src="https://user-images.githubusercontent.com/45068169/157533204-688b86ca-f3e7-435c-bce6-8e2096dc518d.png">
 
- In the accommodation availability area  replace sfârși cu **sfârșit** 
<img width="333" alt="Screenshot 2022-03-09 at 22 49 28" src="https://user-images.githubusercontent.com/45068169/157533517-d5680b38-92bc-4020-a3ba-4fb46d13336e.png">

**Comment by beniamin** [comment]
il preiau eu
