### ISSUE TITLE
[URGENT] Save edits on my accommodation returns 500

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#205]
If I am a HOST and i want to edit my property, after editing, when I press Save it returns 500
<img width="333" alt="Screenshot 2022-03-09 at 22 49 28" src="https://user-images.githubusercontent.com/45068169/157534005-9a6d79cd-4328-458b-8a15-4c4168b19edb.png">

**Comment by beniamin** [comment]
verific eu aici
