### ISSUE TITLE
[URGENT] Change all English leftovers to Romanian

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#207]
In the Admin Dashboard, in View accommodation
- Change "Occupied/Capacity" to "Ocupat/Capacitate totala"
<img width="607" alt="Screenshot 2022-03-09 at 23 40 52" src="https://user-images.githubusercontent.com/45068169/157540915-76c6273b-bbed-468b-8869-0871c6fdbfba.png">

- Change "Operation successful" to "Alocare realizată"

**Comment by beniamin** [comment]
il preiau eu
