### ISSUE TITLE
Create: Types of users

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/war-support-un-acoperis#4]
The platform will have following types of users

**Admin**
Admin users are Code4Romania and other entities that will have full rights in the platform. Broadly, Admin users will be able to:  
- Create other types of user accounts
- Approve/Reject a request for creating a user account 
- Approve/Reject a request for housing or a housing offer 
- See list of all requests for housing registered in the platform and manage its entries 
- See list of all the offers for housing registered in the platform and manage its entries 
- Assign housing requests to housing offers

**Trusted**
Trusted users are Public Authorities or NGOs that can submit and request housing without needing confirmation from Admin users. Every trusted account has a property called "Type" that ca either be _Institution_ or _NGO_.
Trusted users can also request housing on behalf of a Refugee. Every available housing or every refugee request submitted by a Trusted account is automatically approved. 

**Host**
Host users are regular people ("persoana fizica") or legal entities ("persoana juridica") who want to provide accomodation for the refugees. Host users can submit accomodation units to be added in the platform (if Admin users approve Hosts' submission).

**Refugee**
Refugee users are civilians (from Ukraine) that need accomodation in Romania. The Refugee users are created when they submit a housing request in the platform. They can see their request details, wait for the Admin to approve their submission, then wait for the Admin to assign a housing offer to the Refugee's submission. 
Refugee users can also see informative content on the platform.

**Comment by overeha** [comment]
Extra info regarding use cases for Refugee user. 
It is important that the refugee receives an account as it will use this account to see the status of his request, to receive information about the host he is going to once the match is done and to receive information to help him stay safe and identify potential threatening situations (human trafficking signals for instance) 

The platform is not used solely for finding shelter, it is also a support mechanic for immediate need in the long run, even if finding shelter is the main issue. At the border this request can be made after entering the country so it is while entering, can be made even before entering the country in preparation and can be made (most of the cases) once the refugee has reached the camp.

**Comment by lzomedia** [comment]
OK makes sense.

**Comment by mihaibrehar** [comment]
How are admins notified of new accounts? Does this feature already exists?
