### ISSUE TITLE
Form Header

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/war-support-un-acoperis#51]
Above the form there should be a header with
Title - font Titillium Web Semibold, 36px, #1C1080
Paragraph - font Titillium Web Semibold, 16px, #131313 (color user for text all over the webapp)

Info bar:
info icon
![Information circle](https://user-images.githubusercontent.com/95479576/155892728-d5ab7e64-a174-416d-90a8-433913abf1b5.svg)
text

![Form header](https://user-images.githubusercontent.com/95479576/155892376-8fc92715-ac72-49c1-a1fb-ee7cc7f46c2c.PNG)

words & content TBD

**Comment by AndreiGr** [comment]
I'll take this one
