### ISSUE TITLE
Create contact form

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#6]
Create a contact page with a form designed to help NGO-s and Institutions become Trusted accounts (see Issue #4 for what Trusted accounts are). 

The page has:
- title: TBA
- Description: TBA

This contact form has: 
- [INPUT] Institution/Organisation name - **LABEL: Denumire**
- [SINGLE SELECT] Type: Institution / NGO - **LABEL: Tipul solicitantului: Instituție publică / ONG**
- [INPUT] Contact person - LABEL: Persoana de contact
- [INPUT] Email address - **LABEL: Adresa de email**
- [INPUT ] Phone number - **LABEL: Număr de telefon**
- [INPUT] Legal representative name - **LABEL: Numele reprezentantului legal**
- [INPUT] Identification no - **LABEL: Identificator (CUI/Nr de inregistrare in Registrul Asociațiilor și Fundațiilor, după caz)**
- [INPUT] Physical address - **LABEL: Adresa fizica:** 
- [MULTIPLE SELECT] Type of support: Offer housing / Request housing for refugees - **LABEL: Tip de sprijin oferit: Spații de cazare / Solicitări pentru refugiați**

Submit button - **LABEL: Trimite mesaj**

Success page message: Vă mulțumim pentru mesaj, acesta a ajuns la administratorii platformei. Vom reveni cat de curand catre dvs pentru validarea contului de utilizator și cu detalii despre pașii următori. 
The successful submission also send an automatic e-mail to the user with a copy of his message and the following text: 

_Bună ziua, 

vă mulțumim pentru mesajul transmis. 
Mai jos aveți o copie a acestuia. Vom reveni cat de curand catre dvs pentru validarea contului de utilizator și cu detalii despre pașii următori. 
[copy of the messsage]

O zi bună. 
Echipa Code for Romania_

**Comment by verificationcontractor** [comment]
Tiberiu Petre aici, mă pot uita eu peste asta.
