### ISSUE TITLE
Edit account details (for logged in users)

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/war-support-un-acoperis#65]
Logged in users can edit some information in their account, from Sidebar menu -> My account ("Contul meu") -> Section Personal data -> click on "Editeaza" 

In order to change their account details, users need to see prefilled editable fields with old information, modify the fields and click on Save changes button. After clicking they will be redirected to the View my account page

User HOST persoana fizica
Editable personal data:
- Phone number
- Address fields(County, City, Adress)

![HOST pf - edit account](https://user-images.githubusercontent.com/95479576/156031655-213c0e0b-f36d-4d69-b091-e872a0c644df.png)

User HOST persoana juridica
Editable personal data:
- Phone number
- Address fields(County, City, Adress)

![HOST pj - edit account](https://user-images.githubusercontent.com/95479576/156031686-ca00ec8d-90ce-4f03-b3f1-5e395ce4ca0b.png)

User REFUGEE 
![REFUGEE - edit account](https://user-images.githubusercontent.com/95479576/156032063-0a3c522a-25ed-47a2-813f-a7c4047804c6.png)

User TRUSTED 
tbd

**Comment by razvanposobescu** [comment]
@anastk-code4, i can take this one :)
