### ISSUE TITLE
Create counter module for HomePage

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#9]
The homepage must display a counter under the Hero section. The counters are automatic. 

- Total number of Refugee requests
- Total number of housing spaces 
- Total number of occupied housing spaces 

Each counter displays the number, an icon and a label: 

Counter 1:
icon 
Solicitari de ajutor

Counter 2: 
icon
Spatii disponibile

Counter 3: 
icon
Spatii alocate

**Comment by serbanescumihnea** [comment]
Ma ocup

**Comment by serbanescumihnea** [comment]
Counter module done, waiting for Stefan to make necessary translations and push!

**Comment by serbanescumihnea** [comment]
Pull request submitted. #35
